version: "3"
services:
  web2:
    image: php:7.3-apache
    container_name: web2
    hostname: web2
    ports:
      - "81:80"
    volumes:
      - ./sitios/web1:/var/www/html
    environment:
      - VIRTUAL_HOST=web2.com,www.web2.com
    restart: always
    networks:
      - frontend
networks:
  frontend:
